project:
  type: website
  render:
    - "*.qmd"
  output-dir: docs
  
website:
  title: "Medicinska statistika i informatika"
  page-navigation: true
  navbar:
    background: light
    foreground: dark
    right:
      - text: "O meni"
        href: about.qmd
  page-footer:
    center: "&copy; 2024, Nikola Grubor"