---
title: "Testiranje hipoteza o proporcijama"
date: last-modified
author: "Dr Nikola Grubor"
# institute: "Institut za Medicinsku Statistiku i Informatiku"
logo: "slike/logo.png"
lang: sr-Latn
---
```{r}
library(glue)
library(here)
library(tidyverse)
library(tinytable)
library(gtsummary)
source(file = here("theme", "ggthemes.R"))
```

## 

## Hi-kvardrat simulacija

```{r}
# Set seed for reproducibility
set.seed(123)

# Define the expected proportions (say a 2x3 table)
expected_counts <- matrix(c(30, 50, 20, 40, 30, 60), nrow = 2)

# Simulate actual data based on expected counts using rmultinom()
# Suppose you want to simulate a sample size of 500
simulated_data <- rmultinom(n = 1, size = 500, prob = as.vector(expected_counts/sum(expected_counts)))

# Convert to a matrix to resemble the original structure
simulated_data_matrix <- matrix(simulated_data, nrow = 2)

# Perform chi-square test
chisq_test <- chisq.test(simulated_data_matrix)

# Output the results
print(simulated_data_matrix)
print(chisq_test)

```


## Struktura kursa

```{r}
teme <- c(
  "Uvod u medicinsku statistiku", "Sređivanje podataka",
  "Statističko opisivanje podataka", "Verovatnoća i raspodele verovatnoća",
  "Populacija i uzorak", "Testiranje hipoteza o populacionim prosečnim vrednostima i proporcijama",
  "Testiranje hipoteza o učestalostima", "Testiranje hipoteza o rangovima", "Korelacija",
  "Regresija / Kolokvijum", "Podaci, informacije i znanje", "Zdravstveni informacioni sistem",
  "Mere dijagnostičke tačnosti", "Medicinsko odlučivanje", "Bioinformatika"
)

kurs <- tibble(Nedelja = 1:15, Tema = teme)
tt(kurs) |> style_tt(j = 1:2, fontsize = 0.55)
```
