---
title: "Testiranje hipoteza o populacionim prosečnim vrednosima i proporcijama"
subtitle: "... i malo o naučnom metodu."
date: last-modified
author: "Dr Nikola Grubor"
# institute: "Institut za Medicinsku Statistiku i Informatiku"
logo: "slike/logo.png"
lang: sr-Latn
---
```{r}
library(glue)
library(here)
library(tidyverse)
library(tinytable)
library(gtsummary)
source(file = here("slides", "theme", "ggthemes.R"))
```

## 

## Načinite svoje teorije složenim

## Struktura kursa

```{r}
teme <- c(
  "Uvod u medicinsku statistiku", "Sređivanje podataka",
  "Statističko opisivanje podataka", "Verovatnoća i raspodele verovatnoća",
  "Populacija i uzorak", "Testiranje hipoteza o populacionim prosečnim vrednostima i proporcijama",
  "Testiranje hipoteza o učestalostima", "Testiranje hipoteza o rangovima", "Korelacija",
  "Regresija / Kolokvijum", "Podaci, informacije i znanje", "Zdravstveni informacioni sistem",
  "Mere dijagnostičke tačnosti", "Medicinsko odlučivanje", "Bioinformatika"
)

kurs <- tibble(Nedelja = 1:15, Tema = teme)
tt(kurs) |> style_tt(j = 1:2, fontsize = 0.55)
```
